name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0' # or another version as needed

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        working-directory: ./LibBMS
        run: dotnet build

      - name: Run Tests
        working-directory: ./LibBMS.Tests
        run: dotnet test
